[features]
seeds = false

[programs.localnet]
recurring = "4AWRyt6whM4M8C4rimokJxvDP6bts7NxWNxZuyFVKD31"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
